### PR TITLE
NavBar UI Re-Work

### PR DESCRIPTION
**Pull request by sbrenner132**
# NavBar UI Re-Work

Re-worked `NavBar` UI.

[NavBar UI Re-Work](https://trello.com/c/EWzkO0Ff/79-navbar-ui-re-work)

## Changes Made

Changed basic styling and `mui` components used in `NavBar`. It is mobile-web friendly, but does not always scale properly depending on the page shown. **For any pages re-written to change the UI, make sure the `NavBar` looks properly-scaled in mobile view**.

## Reason for changes

- [x] New feature
- [ ] Bug fix
- [ ] Library upgrade(s)

### CODE REVIEW

**Comment by Zeng-Lecheng** [comment]
Tested on my laptop and phone. It looks good on desktop view but on my phone it's like this:
photo_2022-10-12_22-53-22
Not sure if it's been there before or is from changes in this PR. Same thing on my iPad and mobile view simulator on laptop.

**Comment by Zeng-Lecheng** [comment]
> Tested on my laptop and phone. It looks good on desktop view but on my phone it's like this:  Not sure if it's been there before or is from changes in this PR. Same thing on my iPad and mobile view simulator on laptop.

Tested on the main branch and turned out to be the same. Then it should not be this PR.

**Comment by sbrenner132** [comment]
@Zeng-Lecheng Yeah, I didn't touch the login page - that'll probably be next on the list for me. Only changes were to the nav bar, which can still look weird/scaled down on some pages (in mobile view), but will go away when they're refactored. Main thing I just wanna see is that the navigation drawer opens properly in mobile view, and that some of the animations and styling are consistent.

**Review by Zeng-Lecheng — DISMISSED** [review]
Yeah, shuttle schedules are tiny on mobile. Drawer works well, animations are good.

**Comment by sbrenner132** [comment]
@Zeng-Lecheng I removed the fade-in underline animation because there were some bugs with lingering pixels, and removed the icons from the full/desktop view because I thought they took up too much space. I think you might need to re-approve, but everything else is the same.

**Pull request merged**
