### PR TITLE
Add KnowledgeBase Page

### PR DESCRIPTION
**Pull request by yanxuanshaozhu**
# [Add knowledge base page]

Add a page containing knowledge base articles

[Add KnowledgeBase Page](https://trello.com/c/OfUYqQyg/70-add-knowledgebase-page)

## Changes Made
<ul>
<li>Added pages/knowledge-base.js, this is a container for the knowledgebase page</li>
<li>Added components/AppKbView.js, this is the parent of the AppKbDisplay and AppKbForm</li>
<li>Added components/AppKbDisplay.js, this page is for displaying, updating and deleting knowledgebase articles</li>
<li>Added components/AppKbForm.js, this page is for adding new knowledgebase articles</>
<li>Modified components/navbar/linksData.json, so the knowledgebase page is included</li>
<li>Modified pages/api/getinfo/kb/getAppKb/index.js, so it could accept get/post/put/delete requests</li>
<li>Modified utils/rolesUtils.mjs, so now manager roles have access the the knowledgebase page</li>
</ul>

## Reason for changes

- [x] New feature
- [ ] Bug fix
- [ ] Library upgrade(s)

### CODE REVIEW

**Review by sbrenner132 — CHANGES_REQUESTED** [review]
Overall, the code style looks really good! I think there are some spots we can optimize in the future (like not having to re-fetch on every time data is changed and just cache locally, but for now I think this works well). The only thing that doesn't seem to work is editing/updating a KB entry - I think the MongoDB query in the `PUT` request of the API endpoint is returning a null KB document. Was this something that came up while you were working on it?

**Comment by yanxuanshaozhu** [comment]
> Overall, the code style looks really good! I think there are some spots we can optimize in the future (like not having to re-fetch on every time data is changed and just cache locally, but for now I think this works well). The only thing that doesn't seem to work is editing/updating a KB entry - I think the MongoDB query in the `PUT` request of the API endpoint is returning a null KB document. Was this something that came up while you were working on it?

It's kind of tricky that currently the user can only update either the title or the content of a KB, but not both, because our MongoDB KB model does not contain an id for referencing a KB. Also when updating a KB, the user needs to input both the title and the content: one can change and the other one needs to remain the same in order for the PUT request to function properly.

**Comment by yanxuanshaozhu** [comment]
> @yanxuanshaozhu Maybe in that case we can add an ID to the schema? And, when we create a new KB entry, we can just assign a generated UUID or something, and include that as part of the data sent to the `PUT` request so we know what to change.
> 
> We'd have to go and add IDs to the old entries, but what do you think about this?

I'm fun with updating the DB schema, but I'm not sure if this will affect the app. Maybe we need to coordinate with the frontend team and update both the development DB and the production DB.

**Comment by sbrenner132** [comment]
> > @yanxuanshaozhu Maybe in that case we can add an ID to the schema? And, when we create a new KB entry, we can just assign a generated UUID or something, and include that as part of the data sent to the `PUT` request so we know what to change.
> > We'd have to go and add IDs to the old entries, but what do you think about this?
> 
> I'm fun with updating the DB schema, but I'm not sure if this will affect the app. Maybe we need to coordinate with the frontend team and update both the development DB and the production DB.

This shouldn't affect the app, since the only route the app was using was `GET`, which just returns all of the KB entries in the DB. I don't think adding the ID field should change anything on the frontend.

**Review by sbrenner132 — APPROVED** [review]
LGTM now! We might be able to make some changes for caching/UI in the future, but for our uses now this looks amazing!

**Pull request merged**
