### PR TITLE
Push Notifications Page and Register Page UI Re-Work, Add Clubs Page

### PR DESCRIPTION
**Pull request by sbrenner132**
# Push Notifications Page and Register Page UI Re-Work, Add Clubs Page

Re-worked 2 pages and added a third:
- Register page (now has associated clubs/push notification org access)
- Push Notifications page (now can schedule notifications)
- Club page (new - adds ability to add clubs and make clubs 'approved' for push notifications and edit max messages count)

[Push Notifications Page and Register Page UI Re-Work, Add Clubs Page](https://trello.com/c/TNRHKhnY/20-push-notifications-page-and-register-page-ui-re-work-add-clubs-page)

## Changes Made

Changed the following:
- Added orgs/clubs field to `User` model
- Added clubs page, which consists of cards of club info (name, member count, max messages, and some action icons)
- Added `PushNotifications` model for scheduled notifications
- Added cron job to run appropriate route for checking and sending appropriate scheduled push notifications
- Expanded push notification form to include scheduling feature

**Notes for reviewers**: Please don't send test messages to 'General', as **it will send to everyone**. If you want to be added to the test notifications 'club', please let me know! Any test notifications should be sent to 'Test Notifications Club'.

## Reason for changes

- [x] New feature
- [ ] Bug fix
- [ ] Library upgrade(s)

### CODE REVIEW

**Review by Zeng-Lecheng — COMMENTED** [review]
Tried the new things out. It looked like everything worked as intended. It's allowed to register an `Organization Manager` without specifying a `Push Notification Access`. Is this also intended?

**Comment by sbrenner132** [comment]
@Zeng-Lecheng That is intended, and in that case it will grant access to all clubs. Since I will mostly be the one registering users, this shouldn't be an issue, but we can make this clearer down the line if needed

**Review by Zeng-Lecheng — DISMISSED** [review]
Should be good then

**Comment by sbrenner132** [comment]
@Zeng-Lecheng Just made a couple changes with some logging stuff and getting rid of a bad test, another approval so I can get this merged is much appreciated!

**Review by Zeng-Lecheng — APPROVED** [review]
Absolutely no problem!

**Pull request merged**
